apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpbin-cert
spec:
  secretName: httpbin-tls
  issuerRef:
    name: letsencrypt-eks  # Change to letsencrypt-gke for GKE
    kind: ClusterIssuer
  commonName: "example.com"
  dnsNames:
  - "example.com"
